// Generated by CoffeeScript 1.10.0
var React = require('react')
var ReactDOM = require('react-dom')
var $ = require('jquery')
var OpenStreetEditor = require('../components/editor').default
var helper = require('./helper').default

export default {
  init: function($textarea) {
    var $componentPlace, coordinates, coordinatesValuesString, error, exception, propsOpenStreetMap;
    propsOpenStreetMap = {
      onUpdate: (function(_this) {
        return function(coord) {
          return $textarea.val(helper.checkIfDefaults(coord) ? '' : JSON.stringify(coord));
        };
      })(this),
      address: $textarea.data('address')
    };
    try {
      coordinatesValuesString = $textarea.val();
      coordinates = $.parseJSON(coordinatesValuesString);
      propsOpenStreetMap.coordinates = coordinates;
    } catch (error) {
      exception = error;
      if (coordinatesValuesString) {
        console.log("Niepoprawny JSON", coordinatesValuesString);
        console.error(exception);
      }
    }
    $componentPlace = $('<div>Renderowanie edytora OpenStreetMaps...</div>');
    $textarea.after($componentPlace).hide();
    if (helper.valid(propsOpenStreetMap.coordinates)) {
      return ReactDOM.render(React.createElement(OpenStreetEditor, propsOpenStreetMap), $componentPlace[0]);
    }
  }
}
