// Generated by CoffeeScript 1.10.0
var $ = require('jquery')

export default {
  valid: function(coordinates) {
    var valid;
    valid = (coordinates == null) || coordinates.x1 && coordinates.x2 && coordinates.x3 && coordinates.y1 && coordinates.y2 && coordinates.y3 && Object.values(coordinates).every($.isNumeric);
    if (!valid) {
      console.log('Niepoprawny format danych coordynatów do openStreetMap (zobacz OpenStreetMap/viewer.coffee):', coordinates);
    }
    return valid;
  },
  checkIfDefaults: function(coordinates) {
    return parseFloat(coordinates.x1) === 0 && parseFloat(coordinates.x2) === 0 && parseFloat(coordinates.x3) === 0 && parseFloat(coordinates.y1) === 0 && parseFloat(coordinates.y2) === 0 && parseFloat(coordinates.y3) === 0;
  }
}
