// Generated by CoffeeScript 1.10.0
var React = require('react')
var ReactDOM = require('react-dom')
var $ = require('jquery')
var OpenStreetViewer = require('../components/viewer').default
var helper = require('./helper').default


export default {
  init: function($node) {
    var coordinates;
    coordinates = $node.data('coordinates');
    if (helper.valid(coordinates)) {
      return ReactDOM.render(React.createElement(OpenStreetViewer, {
        coordinates: coordinates
      }), $node[0]);
    }
  }
}
